server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CATALOGO-SERVICE
          uri: lb://CATALOGO-SERVICE
          predicates:
            - Path=/categorias/**, /items/**
        - id: LOJA-SERVICE
          uri: lb://LOJA-SERVICE
          predicates:
            - Path=/infoloja/**, /clientes/**, /pedidos/**, /pedidoitems/**, /catalogo/**
        - id: TRANSPORTADORA-SERVICE
          uri: lb://TRANSPORTADORA-SERVICE
          predicates:
            - Path=/transportes/**