server:
  port: 8081

spring:
  application:
    name: CATALOGO-SERVICE
  datasource: 
    url: 'jdbc:mysql://localhost/catalogo?createDatabaseIfNotExist=true&serverTimezone=UTC'
    username: vinicius
    password: 'vinicius_123A'
  jpa:
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true